// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_w[] = {0x3eac199c, 0x3e670cdd, 0xbea73116, 0xbe9e2ea8, 0x3e0830a6};
static const uint64_t gold64_w[] = {0x3fd58333daa253c0ull, 0x3fcce19ac4d18198ull, 0xbfd4e622b693a1e7ull, 0xbfd3c5d4aece9fa8ull, 0x3fc10614e33dca12ull};
static const uint32_t gold32_mse[] = {0x3e886901};
static const uint64_t gold64_mse[] = {0x3fd10d2040fef5a8ull};
static const long goldi_correct[] = {50};
