// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_w[] = {0x3eac199c, 0x3e670cdd, 0xbea73117, 0xbe9e2ea5, 0x3e0830a8};
static const uint64_t gold64_w[] = {0x3fd58333daa23908ull, 0x3fcce19ac4d16377ull, 0xbfd4e622b6939935ull, 0xbfd3c5d4aece93f4ull, 0x3fc10614e33dbd20ull};
static const uint32_t gold32_mse[] = {0x3e886901};
static const uint64_t gold64_mse[] = {0x3fd10d2040ff1567ull};
static const long goldi_correct[] = {50};
