// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_poly[] = {0x00000000, 0x35a00000, 0x34c00000, 0xb4000000, 0x34000000, 0x35c00000, 0xb4c00000, 0x35200000};
static const uint64_t gold64_poly[] = {0xbe7ad7f29d800000ull, 0xbe0ad7f080000000ull, 0xbcfa800000000000ull, 0x3cec000000000000ull, 0xbce2000000000000ull, 0x3d02000000000000ull, 0x3e0ad7ea80000000ull, 0x3e7ad7f293000000ull};
static const uint32_t gold32_sin[] = {0x3ef57744, 0x3f576aa4, 0x3f68c7b8, 0x3e1081b4};
static const uint64_t gold64_sin[] = {0x3fdeaee8744b05f0ull, 0x3feaed548f090ceeull, 0x3fed18f6ead24a7cull, 0x3fc2103881cce7f0ull};
