// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_centroid[] = {0x40a03126, 0x405ac084, 0x3fbb645a, 0x3e79db21, 0x40bcda04, 0x402fe594, 0x408c97f4, 0x3fb78917, 0x40db3331, 0x4044b73e, 0x40b7bf53, 0x40048c21};
static const uint64_t gold64_centroid[] = {0x40140624dd2f1a9full, 0x400b5810624dd2f3ull, 0x3ff76c8b43958106ull, 0x3fcf3b645a1cac05ull, 0x40179b4069b4069cull, 0x4005fcb25fcb25feull, 0x401192fe592fe594ull, 0x3ff6f122af122af2ull, 0x401b666666666667ull, 0x400896e7bf53896dull, 0x4016f7ea712dcf7dull, 0x400091840ac76918ull};
static const long goldi_size[] = {50, 62, 38};
