// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_dist[] = {0x00000000, 0x3c23d6f6, 0x3da3d71c, 0x3db851ee, 0x3de147bc, 0x3de147bc, 0x3df5c294};
static const uint64_t gold64_dist[] = {0x0000000000000000ull, 0x3f847ae147ae14b8ull, 0x3fb47ae147ae1485ull, 0x3fb70a3d70a3d709ull, 0x3fbc28f5c28f5c42ull, 0x3fbc28f5c28f5c44ull, 0x3fbeb851eb851eb0ull};
static const long goldi_class[] = {0, 1, 2, 2};
