// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_w[] = {0x3c0ef31c, 0xbdc03065, 0x3ec7e55b, 0xbce7b9c2};
static const uint64_t gold64_w[] = {0x3f81de5c53a765e0ull, 0xbfb8060c58a88c5eull, 0x3fd8fcaba8c40c3bull, 0xbf9cf7395baa8875ull};
static const uint32_t gold32_loss[] = {0x3d4197ae};
static const uint64_t gold64_loss[] = {0x3fa832f52202f1c5ull};
