// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_x[] = {0x3dd50467, 0x3ea6f50f, 0x3f615e5b, 0x3e86e182, 0x3f2060f1, 0x3f3f1c37};
static const uint64_t gold64_x[] = {0x3fbaa0616cf33aa6ull, 0x3fd4fb3968a972dfull, 0x3fef2188909a7a8dull, 0x3fe21df6f7c5fd7dull, 0x3fcee4b96d4159ecull, 0x3fda6b05e4cda07cull};
