// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_mean[] = {0x40a03126, 0x405ac084, 0x3fbb645a, 0x3e79db21, 0x40bdf3ba, 0x403147ae, 0x408851ec, 0x3fa9ba5d, 0x40d2d0e4, 0x403e5605, 0x40b1a9fd, 0x4001a9fd};
static const uint64_t gold64_mean[] = {0x40140624dd2f1a9full, 0x400b5810624dd2f3ull, 0x3ff76c8b43958106ull, 0x3fcf3b645a1cac05ull, 0x4017be76c8b43958ull, 0x400628f5c28f5c2aull, 0x40110a3d70a3d70aull, 0x3ff5374bc6a7ef9dull, 0x401a5a1cac083125ull, 0x4007cac083126e97ull, 0x4016353f7ced9168ull, 0x4000353f7ced9168ull};
static const uint32_t gold32_var[] = {0x3df95f61, 0x3e11b0cc, 0x3cf1b266, 0x3c388ca3, 0x3e85af6d, 0x3dc5a1cc, 0x3e5d97f7, 0x3d1cf9a1, 0x3ecae211, 0x3dd0bd8c, 0x3e98d475, 0x3d97657a};
static const uint64_t gold64_var[] = {0x3fbf2becedd4844cull, 0x3fc236199780baa6ull, 0x3f9e364bec679ccaull, 0x3f8711947cfa26a0ull, 0x3fd0b5ed8d36b4caull, 0x3fb8b4395810624full, 0x3fcbb2fec56d5cffull, 0x3fa39f340d4dc65aull, 0x3fd95c422036006cull, 0x3fba17b0f6ad70ecull, 0x3fd31a8ef77f2802ull, 0x3fb2ecaeea63b688ull};
static const uint32_t gold32_likelihood[] = {0x43158f4a, 0x420dff94, 0x40f36c76, 0x4168ff0e};
static const uint64_t gold64_likelihood[] = {0x4062b1eb005cb5b3ull, 0x4041bff202b9cac2ull, 0x401e6d927436f985ull, 0x402d1fe08bcb5430ull};
static const long goldi_class[] = {0, 1, 2, 2};
