// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_add[] = {0x40880000, 0xc0600000, 0x453b8004, 0x00000000, 0x3e99999a, 0x42f6e579};
static const uint64_t gold64_add[] = {0x4011000000000000ull, 0xc00c000000000000ull, 0x40a7700083126e98ull, 0x0000000000000000ull, 0x3fd3333333333334ull, 0x405edcaf1a9fbe77ull};
static const uint32_t gold32_sub[] = {0xbfa00000, 0xc0900000, 0xc53b7ffc, 0x41600000, 0xbdcccccd, 0x42f6ed79};
static const uint64_t gold64_sub[] = {0xbff4000000000000ull, 0xc012000000000000ull, 0xc0a76fff7ced9168ull, 0x402c000000000000ull, 0xbfb999999999999aull, 0x405eddaf1a9fbe77ull};
static const uint32_t gold32_mul[] = {0x40840000, 0xc0000000, 0x40400001, 0xc2440000, 0x3ca3d70b, 0xbf76e979};
static const uint64_t gold64_mul[] = {0x4010800000000000ull, 0xc000000000000000ull, 0x4008000000000000ull, 0xc048800000000000ull, 0x3f947ae147ae147cull, 0xbfeedd2f1a9fbe77ull};
static const uint32_t gold32_div[] = {0x3f0ba2e8, 0xc1000000, 0x34b2f4fc, 0xbf800000, 0x3f000000, 0xc676e979};
static const uint64_t gold64_div[] = {0x3fe1745d1745d174ull, 0xc020000000000000ull, 0x3e965e9f80f29211ull, 0xbff0000000000000ull, 0x3fe0000000000000ull, 0xc0cedd2f1a9fbe77ull};
static const uint32_t gold32_min[] = {0x3fc00000, 0xc0800000, 0x3a83126f, 0xc0e00000, 0x3dcccccd, 0xbc000000};
static const uint64_t gold64_min[] = {0x3ff8000000000000ull, 0xc010000000000000ull, 0x3f50624dd2f1a9fcull, 0xc01c000000000000ull, 0x3fb999999999999aull, 0xbf80000000000000ull};
static const uint32_t gold32_max[] = {0x40300000, 0x3f000000, 0x453b8000, 0x40e00000, 0x3e4ccccd, 0x42f6e979};
static const uint64_t gold64_max[] = {0x4006000000000000ull, 0x3fe0000000000000ull, 0x40a7700000000000ull, 0x401c000000000000ull, 0x3fc999999999999aull, 0x405edd2f1a9fbe77ull};
static const uint32_t gold32_sqrt[] = {0x3f9cc471, 0x40000000, 0x3d0186e3, 0x402953fd, 0x3ea1e89b, 0x4131c6f7};
static const uint64_t gold64_sqrt[] = {0x3ff3988e1409212eull, 0x4000000000000000ull, 0x3fa030dc4ea03a72ull, 0x40052a7fa9d2f8eaull, 0x3fd43d136248490full, 0x402638dee52c80edull};
static const uint32_t gold32_neg[] = {0xbfc00000, 0x40800000, 0xba83126f, 0xc0e00000, 0xbdcccccd, 0xc2f6e979};
static const uint64_t gold64_neg[] = {0xbff8000000000000ull, 0x4010000000000000ull, 0xbf50624dd2f1a9fcull, 0xc01c000000000000ull, 0xbfb999999999999aull, 0xc05edd2f1a9fbe77ull};
static const uint32_t gold32_abs[] = {0x3fc00000, 0x40800000, 0x3a83126f, 0x40e00000, 0x3dcccccd, 0x42f6e979};
static const uint64_t gold64_abs[] = {0x3ff8000000000000ull, 0x4010000000000000ull, 0x3f50624dd2f1a9fcull, 0x401c000000000000ull, 0x3fb999999999999aull, 0x405edd2f1a9fbe77ull};
static const uint32_t gold32_from_int[] = {0x00000000, 0x3f800000, 0xbf800000, 0x447a0000, 0xc47a0000, 0x4996b438, 0xcb800000};
static const uint64_t gold64_from_int[] = {0x0000000000000000ull, 0x3ff0000000000000ull, 0xbff0000000000000ull, 0x408f400000000000ull, 0xc08f400000000000ull, 0x4132d68700000000ull, 0xc170000010000000ull};
static const long goldi_lt[] = {1, 1, 1, 0, 1, 0};
static const long goldi_le[] = {1, 1, 1, 0, 1, 0};
static const long goldi_eq[] = {0, 0, 0, 0, 0, 0};
static const long goldi_gt[] = {0, 0, 0, 1, 0, 1};
static const long goldi_ge[] = {0, 0, 0, 1, 0, 1};
static const long goldi_ne[] = {1, 1, 1, 1, 1, 1};
static const long goldi_to_int[] = {15, -40, 0, 70, 1, 1234};
