// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_leibniz[] = {0x4048ff78};
static const uint64_t gold64_leibniz[] = {0x40091fef0a9265ebull};
static const uint32_t gold32_nilakantha[] = {0x40490fdc};
static const uint64_t gold64_nilakantha[] = {0x400921fb502269daull};
static const uint32_t gold32_viete[] = {0x40490fda};
static const uint64_t gold64_viete[] = {0x400921fb544422c3ull};
