// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_newton[] = {0x3fb504f3};
static const uint64_t gold64_newton[] = {0x3ff6a09e667f3bccull};
static const uint32_t gold32_fibonacci[] = {0x3fcf1bbd};
static const uint64_t gold64_fibonacci[] = {0x3ff9e3779b97f4a8ull};
static const uint32_t gold32_rational[] = {0x3fbf09d5};
static const uint64_t gold64_rational[] = {0x3ff7e13aa3549ebfull};
