// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_harmonic[] = {0x40ef890a};
static const uint64_t gold64_harmonic[] = {0x401df11f45f4e618ull};
static const uint32_t gold32_basel[] = {0x3fd26c75};
static const uint64_t gold64_basel[] = {0x3ffa4d8e550a946eull};
static const uint32_t gold32_alt_harmonic[] = {0x3f31513d};
static const uint64_t gold64_alt_harmonic[] = {0x3fe62a2af1bd3636ull};
