// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_naive[] = {0x4479f9c9};
static const uint64_t gold64_naive[] = {0x408f400000000575ull};
static const uint32_t gold32_kahan[] = {0x447a0000};
static const uint64_t gold64_kahan[] = {0x408f400000000000ull};
static const uint32_t gold32_telescope[] = {0x3f7fbe88};
static const uint64_t gold64_telescope[] = {0x3feff7d0f16c2e0eull};
