// Generated by tools/caial.py gold, do not edit.
#define CAIAL_HAVE_GOLD 1

static const uint32_t gold32_w[] = {0xc12f3332, 0xc084ccd0, 0xc10ccccc, 0xc0366663};
static const uint64_t gold64_w[] = {0xc025e6666666666cull, 0xc01099999999999aull, 0xc0219999999999a1ull, 0xc006ccccccccccc9ull};
static const uint32_t gold32_b[] = {0x42b698bb};
static const uint64_t gold64_b[] = {0x4056d3172df39475ull};
static const long goldi_correct[] = {97};
