// Common helpers for the caial tests.
//
// Tests compute with fp_t and report through the macros below. Everything is
// printed as raw bits, the host side (tools/caial.py) decodes and compares:
//
//   @result <name> <idx> <bits> <gold f32 bits> <gold f64 bits>
//   @iresult <name> <idx> <value> <gold>
//   @exact <name> <idx> <decimal>
//   @trace <label> <iter> <bits>
//
// Missing gold values are printed as "-". The gold values come from
// tests/<test>.gold.h, generated by `tools/caial.py gold` from the IEEE runs.

#ifndef CAIAL_H
#define CAIAL_H

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#ifndef FP_BITS
#define FP_BITS 32
#endif

#if FP_BITS == 32
typedef float fp_t;
typedef uint32_t fp_bits_t;
#define FP_C(x) x##f
#define FP_FMT "%08x"
#define fp_sqrt(x) __builtin_sqrtf(x)
#define fp_abs(x) __builtin_fabsf(x)
#elif FP_BITS == 64
typedef double fp_t;
typedef uint64_t fp_bits_t;
#define FP_C(x) x
#define FP_FMT "%016lx"
#define fp_sqrt(x) __builtin_sqrt(x)
#define fp_abs(x) __builtin_fabs(x)
#else
#error "FP_BITS must be 32 or 64"
#endif

#define CAIAL_ARRAY_SIZE(a) (int)(sizeof(a) / sizeof((a)[0]))

static inline fp_bits_t fp_bits(fp_t x) {
  fp_bits_t b;
  memcpy(&b, &x, sizeof(b));
  return b;
}

// gold values for this test, if they were generated already
#define CAIAL_STR_(x) #x
#define CAIAL_STR(x) CAIAL_STR_(x)
#if defined(CAIAL_TEST) && __has_include(CAIAL_STR(CAIAL_TEST.gold.h))
#include CAIAL_STR(CAIAL_TEST.gold.h)
#endif

__attribute__((unused)) static void caial_results(const char *name, const fp_t *v, int n, const uint32_t *g32, const uint64_t *g64,
                          int ngold) {
  for (int i = 0; i < n; i++) {
    printf("@result %s %d " FP_FMT, name, i, fp_bits(v[i]));
    if (i < ngold)
      printf(" %08x %016lx\n", g32[i], (unsigned long)g64[i]);
    else
      printf(" - -\n");
  }
}

__attribute__((unused)) static void caial_iresults(const char *name, const long *v, int n, const long *gold, int ngold) {
  for (int i = 0; i < n; i++) {
    if (i < ngold)
      printf("@iresult %s %d %ld %ld\n", name, i, v[i], gold[i]);
    else
      printf("@iresult %s %d %ld -\n", name, i, v[i]);
  }
}

#ifdef CAIAL_HAVE_GOLD
#define CAIAL_GOLD_ARGS(name) gold32_##name, gold64_##name, CAIAL_ARRAY_SIZE(gold32_##name)
#define CAIAL_IGOLD_ARGS(name) goldi_##name, CAIAL_ARRAY_SIZE(goldi_##name)
#else
#define CAIAL_GOLD_ARGS(name) NULL, NULL, 0
#define CAIAL_IGOLD_ARGS(name) NULL, 0
#endif

// Report n float results (an array) or a single one under a C identifier name.
#define CAIAL_RESULTS(name, values, n) caial_results(#name, values, n, CAIAL_GOLD_ARGS(name))
#define CAIAL_RESULT(name, value)                                                                                      \
  do {                                                                                                                 \
    fp_t caial_v_ = (value);                                                                                           \
    CAIAL_RESULTS(name, &caial_v_, 1);                                                                                 \
  } while (0)

// Integer results (class labels, comparison outcomes, ...).
#define CAIAL_IRESULTS(name, values, n) caial_iresults(#name, values, n, CAIAL_IGOLD_ARGS(name))
#define CAIAL_IRESULT(name, value)                                                                                     \
  do {                                                                                                                 \
    long caial_i_ = (value);                                                                                           \
    CAIAL_IRESULTS(name, &caial_i_, 1);                                                                                \
  } while (0)

// The mathematically exact value of a result, as a decimal string, when known.
#define CAIAL_EXACT(name, idx, decimal) printf("@exact %s %d %s\n", #name, (int)(idx), decimal)

// Per-iteration values, only built with -DCAIAL_TRACE (cmake -DCAIAL_TRACE=ON).
#ifdef CAIAL_TRACE
#define CAIAL_TRACE_VALUE(label, iter, value) printf("@trace %s %d " FP_FMT "\n", label, (int)(iter), fp_bits(value))
#else
#define CAIAL_TRACE_VALUE(label, iter, value) ((void)0)
#endif

#endif // CAIAL_H
